learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from users_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('users_app/',include('users_app.urls')),
    path('admin/', admin.site.urls),
]

learning_users/users_app/urls.py
from django.conf.urls import url
from django.urls import path
from users_app import views

# TEMPLATE URLs
app_name = 'users_app'

urlpatterns = [
    path('register/',views.register,name='register')
]

learning_users/users_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/users_app/forms.py
from django import forms
from django.contrib.auth.models import User
from users_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')        

learning_users/users_app/views.py
from django.shortcuts import render
from users_app.forms import UserProfileInfoForm,UserForm

# Create your views here.
def index(request):
    return render(request,'users_app/index.html')

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'users_app/registration.html',
                            {'user_form':user_form,
                                'profile_form':profile_form,
                                'registered':registered})                    

learning_users/templates/users_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'users_app:register' %}">Register</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

learning_users/templates/users_app/index.html
{% extends "users_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock %}

learning_users/templates/users_app/registration.html
{% extends 'users_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form class="form-group" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" class="btn btn-default" value="Register">
    </form>
  {% endif %}
</div>

{% endblock %}